name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1'  # Adjust depending on your project requirements

    - name: Build with dotnet
      run: dotnet build YourSolution.sln --configuration Release

    - name: Run integration tests
      run: dotnet test YourTestProject/TestProject.csproj --filter Category=Integration
